# Generated by Django 3.2.7 on 2021-11-23 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MO', 'понедельник'), ('TU', 'вторник'), ('WE', 'среда'), ('TH', 'четверг'), ('FR', 'пятница'), ('SA', 'суббота'), ('SU', 'воскресенье')], max_length=2, verbose_name='день недели')),
                ('day', models.IntegerField(verbose_name='день')),
            ],
            options={
                'verbose_name': 'день',
                'verbose_name_plural': 'дни',
            },
        ),
        migrations.CreateModel(
            name='LevelTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_training', models.CharField(max_length=128, unique=True, verbose_name='уровень подготовки')),
            ],
            options={
                'verbose_name': 'уровень подготовки',
                'verbose_name_plural': 'уровень подготовки',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='тренировка')),
                ('purpose', models.CharField(max_length=64, verbose_name='цель')),
                ('cycle_duration', models.IntegerField(verbose_name='длительность цикла')),
                ('training_time_ot', models.IntegerField(verbose_name='время тренировки от')),
                ('training_time_do', models.IntegerField(verbose_name='время тренировки до')),
                ('training_sessions_per_week', models.IntegerField(verbose_name='тренировок в неделю')),
                ('level_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.leveltraining')),
            ],
            options={
                'verbose_name': 'тренировка',
                'verbose_name_plural': 'тренировки',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_place', models.CharField(max_length=128, unique=True, verbose_name='место тренировок')),
            ],
            options={
                'verbose_name': 'место тренировок',
                'verbose_name_plural': 'место тренировок',
            },
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(verbose_name='неделя')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.training')),
            ],
            options={
                'verbose_name': 'неделя',
                'verbose_name_plural': 'недели',
            },
        ),
        migrations.AddField(
            model_name='training',
            name='training_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.trainingplace'),
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='упражнение')),
                ('img', models.ImageField(upload_to='img/', verbose_name='превью')),
                ('video', models.FileField(upload_to='video/', verbose_name='видео')),
                ('repetitions', models.IntegerField(verbose_name='повторений')),
                ('approaches', models.IntegerField(verbose_name='повторов')),
                ('rest', models.IntegerField(verbose_name='отдых (мин)')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.day')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.training')),
            ],
            options={
                'verbose_name': 'упражнение',
                'verbose_name_plural': 'упражнения',
            },
        ),
        migrations.AddField(
            model_name='day',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.training'),
        ),
        migrations.AddField(
            model_name='day',
            name='weeks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.weeks'),
        ),
    ]
