# Generated by Django 3.2.7 on 2021-11-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='cycle_duration',
            field=models.IntegerField(verbose_name='длительность цикла'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_sessions_per_week',
            field=models.IntegerField(verbose_name='длительность цикла'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_time_do',
            field=models.IntegerField(verbose_name='время тренировки до'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_time_ot',
            field=models.IntegerField(verbose_name='время тренировки от'),
        ),
    ]
